services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: puppygraph_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.15.0-community
    container_name: puppygraph_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_dbms_memory_heap_initial__size: '512m'
      NEO4J_dbms_memory_heap_max__size: '2G'
      NEO4J_dbms_memory_pagecache_size: '512m'
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PuppyGraph
  puppygraph:
    image: puppygraph/puppygraph:stable
    container_name: puppygraph_puppygraph
    environment:
      PUPPYGRAPH_PASSWORD: puppygraph123
      QUERY_TIMEOUT: 5m
    ports:
      - "8081:8081"  # HTTP API
      - "8182:8182"  # Gremlin
    volumes:
      - ./data:/data:ro  # Mount data directory as read-only
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
